# Generated by Django 5.2 on 2025-04-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, max_length=2048, unique=True, verbose_name='Page URL')),
                ('domain', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Domain')),
                ('title', models.CharField(blank=True, max_length=512, verbose_name='Page Title')),
                ('summary', models.TextField(blank=True, verbose_name='Summary / Meta Description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20, verbose_name='Crawl Status')),
                ('crawled_at', models.DateTimeField(auto_now_add=True, verbose_name='Crawled At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
            ],
            options={
                'verbose_name': 'Crawled Page',
                'verbose_name_plural': 'Crawled Pages',
                'ordering': ['-updated_at'],
            },
        ),
    ]
