# Generated by Django 4.2.20 on 2025-04-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_crawledpage_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawledpage',
            name='html_content',
            field=models.TextField(blank=True, null=True, verbose_name='Raw HTML Content'),
        ),
    ]
